### ISSUE TITLE
activate CORS

### ISSUE THREAD

**Issue by species** [TransforMap/docker-wikibase-query-service#4]
currently, CORS is not enforced, in contrast to query.wikidata.org.

As this project should be accessible worldwide, we should allow cross-domain requests.

*Edit:* Added `not`.

**Comment by almereyda** [comment]
We need to add `add_header 'Access-Control-Allow-Origin' '*';` to `query.base.transformap.co` in `vhost.d`.

**Comment by almereyda** [comment]
[Nginx needs this in the location directive](http://serverfault.com/questions/162429/how-do-i-add-access-control-allow-origin-in-nginx), while we use [a reverse proxy where we can add such configurations on a per-host basis](https://github.com/jwilder/nginx-proxy#per-virtual_host-location-configuration), but the file in `vhost.d` needs to be named not only after the domain, but suffixed with `_location`, such as `query.base.transformap.co_location`.

**Comment by almereyda** [comment]
This seems to have fixed it.
